name: Build presenations and refresh release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile latex presentations
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            09.tex
            10.tex
            11.tex
            12.tex
            13.tex
          latexmk_shell_escape: true
      - name: Upload generated pdfs to a release
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete v0.0.1
          gh release create v0.0.1 ./*.pdf
