name: Bulid beamer presenations
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
#       - name: Compile latex documents
#         uses: xu-cheng/latex-action@v2
#         with:
#           root_file: |
#             10.tex
#             11.tex
#             12.tex
#             13.tex
#           latexmk_shell_escape: true
      - name: Upload generated pdfs to a release
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_REPO_SECRET }}"
        run: |
          gh release create v0.0.1 *.tex -R https://github.com/BoZenKhaa/PDV-tutorials-pdf
